title: osysHome
description: Документация osysHome
theme: just-the-docs
logo: "/assets/images/logo.png"

search_enabled: true

nav_enabled: true

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/Anisan/osysHome
