title: osysHome
description: Документация osysHome
theme: just-the-docs
logo: "/assets/images/logo.png"

search_enabled: true

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
